### PR TITLE
updated fmri_connectivity nb

### PR DESCRIPTION
**Pull request by Davi1990**
I have updated the following in the jupyter-notebook:

- Now we are using Schaefer atlas (200 parcels and 7 Network)
- I've added a part for resampling the atlas to fmri
- In general I polished and updated the old function 

Please let me know your thoughts 

Dave

### CODE REVIEW

**Comment by htwangtw** [comment]
Question - why change the atlas? I don't see a real reason for this

**Comment by Davi1990** [comment]
First, mostly of the ppl in neuroimaging use Network-based parcellation and I think is important for the students familiarize with that. Second, in the previous example there was not mentioning on resampling which is an important step for FC. Third, I was asked to update the content (in case necessary). If you think is not necessary simply reject and go with previous version ¯\_(ツ)_/¯

**Comment by clarkenj** [comment]
Closes #172

**Comment by htwangtw** [comment]
We decided to reject this PR based on a few things:
1. the original content was working except the utf-8 string formatting
2. it was a deliberate choice to use MIST as the demo
3. some extra content are the answers to the exercises so we don't really want that...

We will add the content related to resampling in the text.
Thanks for the suggestions

**Pull request closed without merging**
