### PR TITLE
Converted the "locations" tab into a collection of posts, one per site.

### LINKED ISSUE #300: update location list
It's all (well except the images) in ./content/en/locations/index.md and ./content/fr/locations/index.md for the French version

### PR DESCRIPTION
**Pull request by pbellec**
This is a key step to fix #300 

I've filled in details for UdeM, and started a blurb for humai and poly. I suggest we merge and then ask each site to add their details through emails.

### CODE REVIEW

**Comment by pbellec** [comment]
Also, note that I removed the "schedule" tab. Instead, I've inserted a google calendar in the "udem" site. I suggest we do that for every site.

**Review by complexbrains — APPROVED** [review]
LGTM! Working nicely at my end!

**Comment by complexbrains** [comment]
Just with a note there is a button looking square at the bottom of the images of the school. Was it meant to be look that way? 
image

**Comment by pbellec** [comment]
Thanks for catching this Isil! I've fixed it. I've also added Magburg. Once I have all the sites I'll merge, and ping each site to update their page as needed.

**Pull request merged**
