### PR TITLE
upload a page for my project

### PR DESCRIPTION
**Pull request by ArunimGuchait**
Closes # .

Changes proposed in this pull request:

-
-

### CODE REVIEW

**Comment by pbellec** [comment]
This PR was not reviewed and is now stale. Closing.

**Comment by ArunimGuchait** [comment]
> This PR was not reviewed and is now stale. Closing.

Professor Bellec,

Thank you for your update. I apologize for any delays. 

If there are specific concerns or additional changes needed, I’m more than willing to address them promptly.

Thank you for your understanding and consideration.

**Comment by pbellec** [comment]
Alright I'm going to do a quick review myself and get back to you.

**Comment by pbellec** [comment]
Thanks for submitting this awesome project! LGTM merging

**Review by pbellec — APPROVED** [review]

**Comment by pbellec** [comment]
project is published here https://school-brainhack.github.io/project/arunim_guchait_project/ :tada:

**Comment by ArunimGuchait** [comment]
> project is published here https://school-brainhack.github.io/project/arunim_guchait_project/ 🎉

Professor Bellec,

Thank you so much for reopening and reviewing the PR. I really appreciate your prompt attention and approval.

I'm thrilled to see the project merged and published. If there are any further updates or improvements needed, please feel free to let me know.

Thanks again for your support and guidance throughout this process.

**Pull request merged**
