### PR TITLE
This is a suggested pull request to add mt repo

### PR DESCRIPTION
**Pull request by moqroq**
hello
@complexbrains @me-pic 

could you please add my project.

best
Roqa

### CODE REVIEW

**Comment by me-pic** [comment]
@moqroq Thank you ! We'll review it and notify you if changes are required

**Comment by moqroq** [comment]
Hello Marie
Thank you for your email
Best
Roqa
________________________________

**Comment by moqroq** [comment]
@me-pic hello 
I've added the jupyter file
please let me know if there is anything I can do 
I appreciate your help
best
Roqa

**Comment by me-pic** [comment]
@moqroq please make sure to follow the instructions as described in the [project guide](https://school-brainhack.github.io/project_guide/). You should not modify that README.md !

**Comment by moqroq** [comment]
@me-pic hello Marie
Sure,
Thank you
best
Roqa

**Comment by pbellec** [comment]
this was merged through a separate PR. Closing this one.

**Pull request closed without merging**
