### PR TITLE
Add spinal cord module

### PR DESCRIPTION
**Pull request by valosekj**
As discussed with @evaalonsoortiz and @benjamindeleener, this PR adds a new module: `Introduction to spinal cord MRI analysis`. 

Note: I'm creating a draft PR, as it will also be reviewed by other members of our lab.

To build and view the website locally, run:

```console
git clone https://github.com/valosekj/school-brainhack.github.io.git
cd school-brainhack.github.io
git checkout jv/add_spinal_cord_module
git submodule update --init --recursive --remote
hugo serve -D

# Then open in your browser:
http://localhost:1313/modules/spinal_cord/
```

Note: If [hugo](https://gohugo.io/) is not installed, follow the steps in their documentation to install it on your machine: https://gohugo.io/getting-started/installing/

### CODE REVIEW

**Comment by evaalonsoortiz** [comment]
How can I view the changes in a website format?

**Comment by htwangtw** [comment]
> How can I view the changes in a website format?

You have to fork the branch and build the website locally.

**Comment by valosekj** [comment]
Actually, when I tried to [build the website locally](https://github.com/school-brainhack/school-brainhack.github.io?tab=readme-ov-file#run-locally), I got the following error:

```console
valosek@macbook-pro:~/code/school-brainhack.github.io$ hugo serve -D
Watching for changes in /Users/valosek/code/school-brainhack.github.io/{content,data,i18n,layouts,static,themes}
Watching for config changes in /Users/valosek/code/school-brainhack.github.io/config.yaml
Start building sites …
hugo v0.125.4+extended darwin/arm64 BuildDate=2024-04-25T13:27:26Z VendorInfo=brew

Built in 177 ms
Error: error building site: render: failed to render pages: render of "page" failed: "/Users/valosek/code/school-brainhack.github.io/layouts/modules/single.html:121:27": execute of template failed: template: modules/single.html:121:27: executing "modules/single.html" at <.Content>: error calling Content: "/Users/valosek/code/school-brainhack.github.io/content/en/modules/installation/index.md:57:1": failed to render shortcode "tabs": "/Users/valosek/code/school-brainhack.github.io/content/en/modules/installation/index.md:1:1": failed to render shortcode "tab": "/Users/valosek/code/school-brainhack.github.io/content/en/modules/installation/index.md:1:1": failed to render shortcode "content": failed to process shortcode: "/Users/valosek/code/school-brainhack.github.io/layouts/shortcodes/content.html:2:22": execute of template failed: template: shortcodes/content.html:2:22: executing "shortcodes/content.html" at <markdownify>: error calling markdownify: "/": execute of template failed: template: _default/_markup/render-link.html:1:14: executing "_default/_markup/render-link.html" at <urls.Parse>: error calling Parse: parse "(https://aka.ms/terminal)": first path segment in URL cannot contain colon
```

**Comment by htwangtw** [comment]
Did you manage to preview your own page after the build even if there's an error?
That looks unrelated to the page you are updating

**Comment by valosekj** [comment]
> Did you manage to preview your own page after the build even if there's an error?
> That looks unrelated to the page you are updating. We can handle this error separately

Nope. It seems that Hugo was unable to successfully build and render the site at all.

**Comment by htwangtw** [comment]
@valosekj - I had a look at the branch and the build seems fine - I couldn't replicate the error
image

Have you tried to update the theme?
```
git submodule update --init --recursive --remote
```

**Comment by valosekj** [comment]
> @valosekj - I had a look at the branch and the build seems fine - I couldn't replicate the error 

Thanks for checking this, @htwangtw!

> Have you tried to update the theme?
> 
> ```
> git submodule update --init --recursive --remote
> ```

Yes, I ran this command.

I have tried to rebuild the page again from scratch using the commands described [here](https://github.com/school-brainhack/school-brainhack.github.io?tab=readme-ov-file#run-locally), but I am still getting the same error:

```console
$ mkdir tmp_brainhack
$ cd tmp_brainhack
$ git clone git@github.com:valosekj/school-brainhack.github.io.git
$ cd school-brainhack.github.io
$ git submodule update --init --recursive --remote
$ hugo serve -D
Watching for changes in /Users/valosek/code/tmp_brainhack/school-brainhack.github.io/{content,data,i18n,layouts,static,themes}
Watching for config changes in /Users/valosek/code/tmp_brainhack/school-brainhack.github.io/config.yaml
Start building sites …
hugo v0.125.4+extended darwin/arm64 BuildDate=2024-04-25T13:27:26Z VendorInfo=brew

Built in 157 ms
Error: error building site: render: failed to render pages: render of "page" failed: "/Users/valosek/code/tmp_brainhack/school-brainhack.github.io/layouts/modules/single.html:121:27": execute of template failed: template: modules/single.html:121:27: executing "modules/single.html" at <.Content>: error calling Content: "/Users/valosek/code/tmp_brainhack/school-brainhack.github.io/content/en/modules/installation/index.md:57:1": failed to render shortcode "tabs": "/Users/valosek/code/tmp_brainhack/school-brainhack.github.io/content/en/modules/installation/index.md:1:1": failed to render shortcode "tab": "/Users/valosek/code/tmp_brainhack/school-brainhack.github.io/content/en/modules/installation/index.md:1:1": failed to render shortcode "content": failed to process shortcode: "/Users/valosek/code/tmp_brainhack/school-brainhack.github.io/layouts/shortcodes/content.html:2:22": execute of template failed: template: shortcodes/content.html:2:22: executing "shortcodes/content.html" at <markdownify>: error calling markdownify: "/": execute of template failed: template: _default/_markup/render-link.html:1:14: executing "_default/_markup/render-link.html" at <urls.Parse>: error calling Parse: parse "(https://aka.ms/terminal)": first path segment in URL cannot contain colon
```

**Comment by htwangtw** [comment]
Can you have the Hugo and MacOS version?

**Comment by valosekj** [comment]
> Can you have the Hugo and MacOS version?

Sure!

```console
valosek@macbook-pro:~$ hugo version
hugo v0.125.4+extended darwin/arm64 BuildDate=2024-04-25T13:27:26Z VendorInfo=brew                                                                                                                               /0.1s
valosek@macbook-pro:~$ sw_vers -productVersion
13.6.3
```

**Comment by htwangtw** [comment]
Interesting - I am on a much older version (`hugo v0.92.2`)
Might worth checking if downgrading helps

**Comment by pbellec** [comment]
On my end I'm going to try and set up the website with a fresh recent Hugo version.  It can be that I missed an error introduced with updates.

**Comment by pbellec** [comment]
I've fixed the issue. You need to merge the current version of the `main` branch and you should be able to do some local builds.

**Comment by valosekj** [comment]
> I've fixed the issue. You need to merge the current version of the `main` branch and you should be able to do some local builds.

Thank you for the fix! I merged the `main` branch into my fork, and I can now confirm that I was able to build the website!
I updated my [first comment](https://github.com/school-brainhack/school-brainhack.github.io/pull/310#issue-2273571313) with commands on how to build and view the website locally.

**Comment by htwangtw** [comment]
Let us know once this is ready for review :)

**Review by jcohenadad — APPROVED** [review]
Amazing!

**Comment by htwangtw** [comment]
The PR is still a draft, let me know if there's any thing you are not sure about before converting it for review. The button and icons should be green once it's converted.

**Comment by valosekj** [comment]
> Let us know once this is ready for review :)

Thank you! The PR has been reviewed by my colleagues and is now ready for your review.

**Review by htwangtw — APPROVED** [review]
LGTM

**Comment by valosekj** [comment]
Thanks for merging! Should I also add the module to the [weeks](https://school-brainhack.github.io/weeks/) page? Potentially to week 2?

**Comment by evaalonsoortiz** [comment]
Great work @valosekj ! I vote yes for adding it to week 2.

**Pull request merged**
