### PR TITLE
Add sleep deprivation project to BHS2023 website

### PR DESCRIPTION
**Pull request by Thomas-Pr**
Changes proposed in this pull request:
- Add project directory with name corresponding to my project (fMRI-sleep-deprivation)
- Edit content of the index.md file
- Add the pictures to use for my project

Please review and add my project to this repository @Andjelaaaa @valosekj
Thank you!

### CODE REVIEW

**Review by Andjelaaaa — COMMENTED** [review]
Hi Thomas,
Great work! I left a comment on your index.md file as a suggestion.

**Review by pbellec — CHANGES_REQUESTED** [review]
on my end the project page renders correctly and the meta-data seems accurate. 
Please address @Andjelaaaa 's comment and I'll merge.

**Comment by Thomas-Pr** [comment]
Hello @pbellec, @Andjelaaaa 's comment was addressed to fix the redundant sub-titles already present in the html content of the index.md file (which was not the case in my original README.md file). Thank you for your suggestion.

**Comment by pbellec** [comment]
LGTM, merging!

**Pull request merged**
